version: 0.0
os: linux
files:
  - source: classifier/*
    destination: /classifer/
hooks:
  ApplicationStop:
    - location: kill_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: build_image.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: ec2-user