version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: kill_container.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_container.sh
      timeout: 300
      runas: ec2-user