version: 0.0
os: linux
files:
  - source: classifier/*
    destination: /classifer/
hooks:
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_image.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ec2-user